{
 "title": "Victoriametrics Dashboard",
 "time": { "from": "2025-04-25T11:06:56.235Z", "to": "2025-04-25T13:38:06.286Z" },
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(api_victoria_http_requests_total) by (method, route, status_code, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Histogram of Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(api_victoria_http_request_duration_ms_bucket[1m])) by (le, method, route, status_code, instance))\n"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(api_victoria_http_errors_total) by (status_code, method, route, instance)"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(api_victoria_http_request_duration_ms) by (method, route, status_code, instance)\n"
    }
   ]
  },
  {
   "title": "Request Rate (Requests per Minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(api_victoria_http_requests_total[1m])) by (method, route, status_code, instance)"
    }
   ]
  },
  {
   "title": "Histogram of Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(api_victoria_http_request_duration_ms_bucket[1m])) by (le, method, route, status_code, instance))"
    }
   ]
  },
  {
   "title": "Total Requests ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(api_victoria_http_requests_total) by (method, route, status_code, instance)\n"
    }
   ]
  },
  {
   "title": "Total Requests  Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(api_victoria_http_errors_total) by (status_code, method, route, instance)\n"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } }
 ]
}